### ISSUE TITLE
Problem deploying in Docker

### ISSUE THREAD

**Issue by adrian-rosello** [T-NOVA/TeNOR#134]
Hi!

When I try to deploy TeNOR using the Dockerfile, everything works fine except when the mongodb database is filled with the admin user. That's the error I get:

```bash
Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set #<Moped::Cluster:47236887580100 @seeds=[<Moped::Node resolved_address="127.0.0.1:27017">]>
/usr/local/bundle/gems/moped-2.0.7/lib/moped/cluster.rb:254:in `with_primary'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `call'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:39:in `rescue in with_retry'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:29:in `with_retry'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/query.rb:128:in `first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:191:in `block in first_with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:135:in `with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:190:in `first_with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:212:in `find_first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `find_first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/findable.rb:110:in `find_by'
/root/TeNOR/ns-manager/Rakefile:23:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set #<Moped::Cluster:47236887580100 @seeds=[<Moped::Node resolved_address="127.0.0.1:27017">]>
/usr/local/bundle/gems/moped-2.0.7/lib/moped/cluster.rb:254:in `with_primary'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `call'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/local/bundle/gems/moped-2.0.7/lib/moped/query.rb:128:in `first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:191:in `block in first_with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:135:in `with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:190:in `first_with_cache'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:212:in `find_first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `find_first'
/usr/local/bundle/gems/mongoid-4.0.2/lib/mongoid/findable.rb:110:in `find_by'
/root/TeNOR/ns-manager/Rakefile:23:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by jbatalle** [comment]
Thanks a lot @adrian-rosello! #135
